import 'arrow_piece.dart';
import 'direction.dart';
import 'level_model.dart';
import 'position.dart';

class SampleLevels {
  static final LevelModel level1 = LevelModel(
    id: 1,
    difficulty: 'easy',
    gridSize: 4,
    cellSize: 64,
    // Only the cells this level uses — a simple cross shape
    boardCells: {
      Position(0, 1),
      Position(0, 2),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(1, 3),
      Position(2, 0),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(3, 1),
      Position(3, 2),
    },
    arrows: [
      const ArrowPiece(
        id: 'a1',
        position: Position(1, 1),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'a2',
        position: Position(2, 2),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'a3',
        position: Position(0, 1),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'a4',
        position: Position(3, 2),
        direction: Direction.down,
      ),
    ],
  );

  static final LevelModel level2 = LevelModel(
    id: 2,
    difficulty: 'easy',
    gridSize: 5,
    cellSize: 64,
    // L-shaped board
    boardCells: {
      Position(0, 0),
      Position(0, 1),
      Position(0, 2),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(2, 0),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(3, 0),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(4, 0),
      Position(4, 1),
      Position(4, 2),
      Position(4, 3),
      Position(4, 4),
    },
    arrows: [
      const ArrowPiece(
        id: 'b1',
        position: Position(0, 0),
        direction: Direction.right,
        length: 2,
      ),
      const ArrowPiece(
        id: 'b2',
        position: Position(1, 2),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'b3',
        position: Position(3, 4),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'b4',
        position: Position(4, 1),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'b5',
        position: Position(2, 3),
        direction: Direction.up,
      ),
    ],
  );

  static final LevelModel level3 = LevelModel(
    id: 3,
    difficulty: 'easy',
    gridSize: 5,
    cellSize: 64,
    // T-shaped board
    boardCells: {
      Position(0, 0),
      Position(0, 1),
      Position(0, 2),
      Position(0, 3),
      Position(0, 4),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(1, 3),
      Position(1, 4),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(4, 1),
      Position(4, 2),
      Position(4, 3),
    },
    arrows: [
      const ArrowPiece(
        id: 'c1',
        position: Position(0, 2),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'c2',
        position: Position(1, 0),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'c3',
        position: Position(1, 4),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'c4',
        position: Position(3, 1),
        direction: Direction.right,
        shape: ArrowShape.lShape,
        turnDirection: Direction.up,
      ),
      const ArrowPiece(
        id: 'c5',
        position: Position(4, 2),
        direction: Direction.down,
      ),
    ],
  );

  static final LevelModel level4 = LevelModel(
    id: 4,
    difficulty: 'medium',
    gridSize: 6,
    cellSize: 60,
    // Irregular — missing corners
    boardCells: {
      Position(0, 1),
      Position(0, 2),
      Position(0, 3),
      Position(0, 4),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(1, 3),
      Position(1, 4),
      Position(1, 5),
      Position(2, 0),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(2, 5),
      Position(3, 0),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(3, 5),
      Position(4, 0),
      Position(4, 1),
      Position(4, 2),
      Position(4, 3),
      Position(4, 4),
      Position(4, 5),
      Position(5, 1),
      Position(5, 2),
      Position(5, 3),
      Position(5, 4),
    },
    arrows: [
      const ArrowPiece(
        id: 'd1',
        position: Position(0, 1),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'd2',
        position: Position(0, 4),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'd3',
        position: Position(2, 0),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'd4',
        position: Position(2, 4),
        direction: Direction.right,
        shape: ArrowShape.lShape,
        turnDirection: Direction.down,
      ),
      const ArrowPiece(
        id: 'd5',
        position: Position(5, 2),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'd6',
        position: Position(3, 3),
        direction: Direction.up,
      ),
    ],
  );

  static final LevelModel level5 = LevelModel(
    id: 5,
    difficulty: 'medium',
    gridSize: 6,
    cellSize: 60,
    // Plus/cross shaped board
    boardCells: {
      Position(0, 2),
      Position(0, 3),
      Position(1, 2),
      Position(1, 3),
      Position(2, 0),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(2, 5),
      Position(3, 0),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(3, 5),
      Position(4, 2),
      Position(4, 3),
      Position(5, 2),
      Position(5, 3),
    },
    arrows: [
      const ArrowPiece(
        id: 'e1',
        position: Position(0, 2),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'e2',
        position: Position(0, 3),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'e3',
        position: Position(2, 0),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'e4',
        position: Position(3, 5),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'e5',
        position: Position(5, 2),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'e6',
        position: Position(3, 1),
        direction: Direction.up,
        shape: ArrowShape.lShape,
        turnDirection: Direction.right,
      ),
    ],
  );

  static final LevelModel level6 = LevelModel(
    id: 6,
    difficulty: 'medium',
    gridSize: 6,
    cellSize: 58,
    // Zigzag staircase board
    boardCells: {
      Position(0, 0),
      Position(0, 1),
      Position(0, 2),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(1, 3),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(3, 5),
      Position(4, 3),
      Position(4, 4),
      Position(4, 5),
      Position(5, 3),
      Position(5, 4),
      Position(5, 5),
    },
    arrows: [
      const ArrowPiece(
        id: 'f1',
        position: Position(0, 0),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'f2',
        position: Position(0, 2),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'f3',
        position: Position(2, 1),
        direction: Direction.left,
        shape: ArrowShape.lShape,
        turnDirection: Direction.down,
      ),
      const ArrowPiece(
        id: 'f4',
        position: Position(3, 5),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'f5',
        position: Position(5, 3),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'f6',
        position: Position(1, 3),
        direction: Direction.down,
        shape: ArrowShape.lShape,
        turnDirection: Direction.right,
      ),
      const ArrowPiece(
        id: 'f7',
        position: Position(4, 3),
        direction: Direction.left,
      ),
    ],
  );

  static final LevelModel level7 = LevelModel(
    id: 7,
    difficulty: 'hard',
    gridSize: 7,
    cellSize: 54,
    // Diamond shaped board
    boardCells: {
      Position(0, 3),
      Position(1, 2),
      Position(1, 3),
      Position(1, 4),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(2, 5),
      Position(3, 0),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(3, 5),
      Position(3, 6),
      Position(4, 1),
      Position(4, 2),
      Position(4, 3),
      Position(4, 4),
      Position(4, 5),
      Position(5, 2),
      Position(5, 3),
      Position(5, 4),
      Position(6, 3),
    },
    arrows: [
      const ArrowPiece(
        id: 'g1',
        position: Position(0, 3),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'g2',
        position: Position(1, 2),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'g3',
        position: Position(1, 4),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'g4',
        position: Position(3, 1),
        direction: Direction.left,
        shape: ArrowShape.lShape,
        turnDirection: Direction.up,
      ),
      const ArrowPiece(
        id: 'g5',
        position: Position(3, 5),
        direction: Direction.right,
        shape: ArrowShape.lShape,
        turnDirection: Direction.down,
      ),
      const ArrowPiece(
        id: 'g6',
        position: Position(5, 2),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'g7',
        position: Position(5, 4),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'g8',
        position: Position(6, 3),
        direction: Direction.down,
      ),
    ],
  );

  static final LevelModel level8 = LevelModel(
    id: 8,
    difficulty: 'hard',
    gridSize: 8,
    cellSize: 52,
    // Irregular with holes in the middle
    boardCells: {
      Position(0, 0),
      Position(0, 1),
      Position(0, 2),
      Position(0, 5),
      Position(0, 6),
      Position(0, 7),
      Position(1, 0),
      Position(1, 1),
      Position(1, 2),
      Position(1, 5),
      Position(1, 6),
      Position(1, 7),
      Position(2, 0),
      Position(2, 1),
      Position(2, 2),
      Position(2, 3),
      Position(2, 4),
      Position(2, 5),
      Position(2, 6),
      Position(2, 7),
      Position(3, 0),
      Position(3, 1),
      Position(3, 2),
      Position(3, 3),
      Position(3, 4),
      Position(3, 5),
      Position(3, 6),
      Position(3, 7),
      Position(4, 0),
      Position(4, 1),
      Position(4, 2),
      Position(4, 3),
      Position(4, 4),
      Position(4, 5),
      Position(4, 6),
      Position(4, 7),
      Position(5, 0),
      Position(5, 1),
      Position(5, 2),
      Position(5, 3),
      Position(5, 4),
      Position(5, 5),
      Position(5, 6),
      Position(5, 7),
      Position(6, 0),
      Position(6, 1),
      Position(6, 2),
      Position(6, 5),
      Position(6, 6),
      Position(6, 7),
      Position(7, 0),
      Position(7, 1),
      Position(7, 2),
      Position(7, 5),
      Position(7, 6),
      Position(7, 7),
    },
    arrows: [
      const ArrowPiece(
        id: 'h1',
        position: Position(0, 0),
        direction: Direction.up,
      ),
      const ArrowPiece(
        id: 'h2',
        position: Position(0, 7),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'h3',
        position: Position(2, 2),
        direction: Direction.right,
        shape: ArrowShape.lShape,
        turnDirection: Direction.up,
      ),
      const ArrowPiece(
        id: 'h4',
        position: Position(2, 5),
        direction: Direction.left,
        shape: ArrowShape.lShape,
        turnDirection: Direction.up,
      ),
      const ArrowPiece(
        id: 'h5',
        position: Position(3, 0),
        direction: Direction.left,
      ),
      const ArrowPiece(
        id: 'h6',
        position: Position(4, 7),
        direction: Direction.right,
      ),
      const ArrowPiece(
        id: 'h7',
        position: Position(5, 2),
        direction: Direction.right,
        shape: ArrowShape.lShape,
        turnDirection: Direction.down,
      ),
      const ArrowPiece(
        id: 'h8',
        position: Position(5, 5),
        direction: Direction.left,
        shape: ArrowShape.lShape,
        turnDirection: Direction.down,
      ),
      const ArrowPiece(
        id: 'h9',
        position: Position(7, 0),
        direction: Direction.down,
      ),
      const ArrowPiece(
        id: 'h10',
        position: Position(7, 7),
        direction: Direction.down,
      ),
    ],
  );

  static final List<LevelModel> all = [
    level1,
    level2,
    level3,
    level4,
    level5,
    level6,
    level7,
    level8,
  ];
}
